const categories = [
  ['iluminacao','💡','Iluminação Pública'], ['buracos','🛣️','Buracos e Pavimentação'],
  ['limpeza','🗑️','Limpeza Urbana'], ['saneamento','🚰','Saneamento Básico'],
  ['seguranca','🚨','Segurança Pública'], ['transporte','🚌','Transporte Público'],
  ['arborizacao','🌳','Arborização'], ['calcada','🧱','Calçada Danificada'],
  ['sinalizacao','🚦','Sinalização de Trânsito'], ['outros','📋','Outros']
];
const starter = { users: [], reports: [], notifications: [], currentUser: null };
let data;
try { data = { ...starter, ...JSON.parse(localStorage.getItem('lumen-demo-data') || '{}') }; }
catch { data = { ...starter }; }
let registration = { step: 1, name: '', email: '', cpf: '', phone: '', city: '', state: '', password: '' };
let reportDraft = { step: 1, category: new URLSearchParams(location.hash.split('?')[1] || '').get('categoria') || '', address: '', district: '', city: '', title: '', description: '', photo: '' };
let listScope = 'mine';
let listFilter = 'Todos';
let toastTimer;

const $ = (selector) => document.querySelector(selector);
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const save = () => localStorage.setItem('lumen-demo-data', JSON.stringify(data));
const path = () => (location.hash.slice(1).split('?')[0] || '/home').replace(/\/$/, '') || '/home';
const href = (p) => `#${p}`;
const name = () => data.currentUser?.name?.split(' ')[0] || 'Cidadão';
const myReports = () => data.reports.filter(r => r.userId && r.userId === data.currentUser?.email);
const counts = (reports = data.reports) => ({ total: reports.length, resolved: reports.filter(r => r.status === 'Resolvido').length, progress: reports.filter(r => r.status === 'Em Andamento').length, pending: reports.filter(r => r.status === 'Pendente').length });
const link = (url, label, cls = '') => `<a class="${cls}" href="${href(url)}">${label}</a>`;
const logo = (dest = '/home') => `<a class="logo" href="${href(dest)}" aria-label="LUMEN, página inicial"><span class="logo-icon">L</span><span>LUMEN</span></a>`;
const buttonLink = (url, label, cls = 'btn-primary') => link(url, label, `btn ${cls}`);
const categoryName = (id) => categories.find(c => c[0] === id)?.[2] || 'Outros';
const sectionTag = (text) => `<span class="eyebrow">${text}</span>`;

function header(inside = false) {
  const current = path();
  const items = inside
    ? [['/dashboard','Dashboard'],['/nova-denuncia','Nova Denúncia'],['/minhas-denuncias','Denúncias'],['/estatisticas','Estatísticas']]
    : [['/home','Início'],['/sobre','Como Funciona'],['/estatisticas','Estatísticas']];
  return `<header class="site-header"><div class="nav-shell">${logo(inside ? '/dashboard' : '/home')}
    <nav class="desktop-nav" aria-label="Navegação principal">${items.map(([url,label]) => link(url,label,current === url ? 'nav-active' : '')).join('')}</nav>
    <div class="header-actions">${inside
      ? `${link('/notificacoes', `🔔${data.notifications.filter(n => n.userId === data.currentUser?.email && !n.read).length ? `<span class="notice-count">${data.notifications.filter(n => n.userId === data.currentUser?.email && !n.read).length}</span>` : ''}`, 'bell-link')}
         <button class="account-button" type="button" data-action="account-menu"><span class="avatar">${esc(name()[0] || 'U')}</span><span>${esc(data.currentUser?.name || 'Usuário')}</span><span>⌄</span></button>`
      : `${link('/login','Entrar','header-login')}${buttonLink('/cadastro','Criar Conta','btn-primary btn-small')}`}
      <button class="menu-toggle" type="button" data-action="toggle-menu" aria-label="Abrir menu">☰</button>
    </div></div><div class="mobile-menu" id="mobile-menu">${items.map(([url,label]) => link(url,label)).join('')}${inside ? link('/configuracoes','Configurações') : link('/login','Entrar')}</div><div class="account-menu" id="account-menu">${link('/configuracoes','⚙️ Configurações')}${link('/home','↗ Página inicial')}<button type="button" data-action="logout">Sair da conta</button></div></header>`;
}

function footer() {
  return `<footer class="footer"><div class="container footer-grid"><div class="footer-brand">${logo()}<p>Conectando cidadãos e administração pública para construir cidades mais seguras, transparentes e humanas.</p>${link('/denuncia-anonima','🔒 Denúncia Anônima','footer-anon')}</div>
  <div><h4>PLATAFORMA</h4>${link('/sobre','Como Funciona')}${link('/estatisticas','Estatísticas')}${link('/nova-denuncia','Fazer Denúncia')}${link('/sobre','Sobre a LUMEN')}</div>
  <div><h4>CONTA</h4>${link('/login','Entrar')}${link('/cadastro','Criar Conta')}${link('/dashboard','Dashboard')}${link('/esqueci-senha','Esqueci a Senha')}</div>
  <div><h4>LEGAL</h4>${link('/termos-de-uso','Termos de Uso')}${link('/politica-de-privacidade','Privacidade')}</div></div><div class="container footer-bottom"><span>© 2024 LUMEN Tecnologia Cívica. Todos os direitos reservados.</span><span>🇧🇷 Feito com propósito no Brasil</span></div></footer>`;
}

function home() {
  const shortCategories = [['💡','Iluminação','iluminacao'],['🛣️','Pavimentação','buracos'],['🚰','Saneamento','saneamento'],['🚦','Sinalização','sinalizacao'],['🌳','Arborização','arborizacao'],['🧱','Calçadas','calcada'],['🚨','Segurança','seguranca'],['📋','Outros','outros']];
  return `${header()}<main><section class="hero"><div class="hero-glow one"></div><div class="hero-glow two"></div><div class="container hero-grid"><div class="hero-copy">${sectionTag('PLATAFORMA CÍVICA DIGITAL')}<h1>Sua voz tem o poder<br>de <em>transformar</em><br>a cidade</h1><p>Registre problemas urbanos e encaminhe-os diretamente às autoridades. Transparente, gratuito e protegido pela LGPD.</p><div class="hero-buttons">${buttonLink('/cadastro','Fazer Denúncia →','btn-green')}${buttonLink('/denuncia-anonima','🔒 Denúncia Anônima','btn-outline')}</div><div class="hero-stats"><div><strong>12.4K+</strong><span>Denúncias registradas</span></div><div><strong>89%</strong><span>Taxa de resolução</span></div><div><strong>&lt; 5 dias</strong><span>Tempo médio</span></div></div></div><div class="hero-art"><img src="https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=720&h=540&fit=crop&auto=format" alt="Vista aérea de cidade" /><div class="float-card solved"><span>✅</span><div><strong>Problema Resolvido!</strong><small>LMN-2024-003 · 4.2 dias</small></div></div><div class="float-card update"><span>🔔</span><div><strong>Atualização</strong><small>Sua denúncia está em andamento</small></div></div></div></div></section>
  <section class="category-strip"><div class="container">${sectionTag('CATEGORIAS DE DENÚNCIA')}<div class="category-row">${shortCategories.map(([icon,label,id]) => link(`/nova-denuncia?categoria=${id}`,`<span>${icon}</span>${label}`,'category-chip')).join('')}</div></div></section>
  <section class="steps-section" id="como-funciona"><div class="container section-center">${sectionTag('SIMPLES E EFICAZ')}<h2>Como o LUMEN funciona</h2><p>Três passos simples para transformar um problema em solução.</p><div class="steps-grid">${[['📍','Identifique o Problema','Fotografe, descreva e localize com precisão. Em menos de 2 minutos pelo celular ou computador.','/nova-denuncia'],['📡','Acompanhe em Tempo Real','Receba notificações sobre cada atualização. Saiba quando foi aceito, encaminhado e resolvido.','/dashboard'],['🏙️','Cidade Transformada','Veja o impacto coletivo. Cada denúncia conta para uma cidade mais segura e justa.','/estatisticas']].map(([icon,title,desc,url],i) => link(url,`<div class="step-number">0${i+1}</div><div class="step-icon">${icon}</div><h3>${title}</h3><p>${desc}</p>`,'step-card')).join('')}</div></div></section>
  <section class="feature-section"><div class="container feature-grid"><div class="feature-copy">${sectionTag('POR QUE LUMEN?')}<h2>Tecnologia cívica<br>a serviço das pessoas</h2><p>Construído com transparência e responsabilidade. Cada recurso foi desenhado para empoderar cidadãos e tornar a gestão pública mais ágil.</p><div class="inline-actions">${buttonLink('/cadastro','Comece gratuitamente','btn-primary')}${link('/sobre','Saiba mais →','text-link')}</div></div><div class="feature-cards">${[['🔓','Transparência Total','Todas as denúncias são públicas. Cidadãos acompanham, apoiam e fiscalizam em conjunto.'],['🔒','Privacidade LGPD','Seus dados protegidos por lei. Modo anônimo disponível — nenhum dado coletado.'],['⚡','Encaminhamento Direto','Integração com sistemas municipais para triagem e encaminhamento automático.'],['📊','Dados Abertos','Estatísticas públicas para jornalistas, pesquisadores e gestores municipais.']].map(([icon,title,desc])=>`<article class="feature-card"><span>${icon}</span><h3>${title}</h3><p>${desc}</p></article>`).join('')}</div></div></section>
  <section class="cta-section"><div class="container cta-box"><div class="cta-orb"></div><h2>Pronto para transformar<br>sua cidade?</h2><p>Junte-se a cidadãos que já estão fazendo a diferença. Gratuito, transparente e protegido pela LGPD.</p><div class="hero-buttons">${buttonLink('/cadastro','Criar conta gratuita →','btn-white')}${buttonLink('/denuncia-anonima','🔒 Denunciar anonimamente','btn-dark-outline')}</div><div class="trust-row">🛡️ 100% LGPD&nbsp;&nbsp; 🆓 Gratuito para sempre&nbsp;&nbsp; 🇧🇷 Feito no Brasil</div></div></section></main>${footer()}`;
}

function authSide(isSignup = false, isRecovery = false) {
  return `<aside class="auth-side"><div class="auth-side-overlay"></div><div class="auth-side-inner">${logo()}<div class="auth-side-copy"><h2>${isSignup ? 'Faça parte da mudança que você quer ver na sua rua.' : isRecovery ? 'Recupere o acesso à sua conta' : 'Seja bem-vindo de volta'}</h2><p>${isSignup ? 'Junte-se a milhares de cidadãos transformando suas cidades com o LUMEN.' : isRecovery ? 'Enviaremos um link seguro para você redefinir sua senha.' : 'Acesse sua conta e continue contribuindo para uma cidade melhor.'}</p><div class="auth-benefits"><div>✓ Gratuito para todos os cidadãos</div><div>✓ Seus dados protegidos pela LGPD</div><div>✓ Resultados reais e mensuráveis</div></div></div>${link('/denuncia-anonima','Prefere denunciar sem cadastro? Clique aqui','auth-side-link')}</div></aside>`;
}
function field(label,id,placeholder,type='text',value='',extra='') { return `<label class="field"><span>${label}</span><input id="${id}" name="${id}" type="${type}" placeholder="${placeholder}" value="${esc(value)}" ${extra}></label>`; }
function login() { return `<main class="auth-layout">${authSide()}<div class="auth-main"><div class="auth-form-wrap">${logo()}<div class="auth-title"><h1>Entrar na conta</h1><p>Não tem conta? ${link('/cadastro','Cadastre-se grátis')}</p></div><form id="login-form" class="form-stack">${field('E-MAIL','email','seu@email.com','email','','required autocomplete="email"')}<div class="field-heading"><span>SENHA</span>${link('/esqueci-senha','Esqueci a senha')}</div><label class="field no-label"><input name="password" type="password" placeholder="••••••••" required autocomplete="current-password"></label><button class="btn btn-primary btn-full" type="submit">Entrar na Conta →</button></form><div class="divider"><span>ou continue com</span></div><button class="btn btn-google btn-full" type="button" data-action="google"><strong>G</strong> Continuar com Google</button><p class="auth-legal">Ao entrar, você concorda com os ${link('/termos-de-uso','Termos de Uso')} e a ${link('/politica-de-privacidade','Política de Privacidade')}.</p>${link('/denuncia-anonima','Prefere fazer uma denúncia anônima?','auth-bottom-link')}</div></div></main>`; }

function signup() {
  const steps = ['Dados Pessoais','Localização','Segurança','Confirmação'];
  let content = '';
  if(registration.step === 1) content = `${field('Nome Completo','reg-name','João da Silva','text',registration.name,'required autocomplete="name"')}${field('E-mail','reg-email','seu@email.com','email',registration.email,'required autocomplete="email"')}${field('CPF','reg-cpf','123.456.789-00','text',registration.cpf,'required inputmode="numeric"')}${field('Telefone (opcional)','reg-phone','(11) 9 1234-5678','tel',registration.phone)}`;
  if(registration.step === 2) content = `${field('Cidade','reg-city','Sua cidade','text',registration.city,'required')}<label class="field"><span>Estado</span><select name="reg-state" required><option value="">Selecione seu estado</option>${['SP','RJ','MG','ES','PR','SC','RS','BA','PE','CE','DF','GO','AM','PA','MT','MS','MA','PB','RN','AL','SE','PI','TO','RO','AC','AP','RR'].map(s=>`<option ${registration.state===s?'selected':''}>${s}</option>`).join('')}</select></label>`;
  if(registration.step === 3) content = `<label class="field"><span>Senha</span><div class="password-control"><input name="reg-password" type="password" placeholder="Crie uma senha segura" value="${esc(registration.password)}" required minlength="6"><button type="button" data-action="toggle-password" aria-label="Mostrar senha">👁️</button></div></label>${field('Confirmar Senha','reg-confirm','Confirme sua senha','password','','required minlength="6"')}<p class="form-hint">Use pelo menos 6 caracteres para proteger sua conta.</p>`;
  if(registration.step === 4) content = `<div class="review-box"><h3>Revise seus dados</h3><p><strong>Nome:</strong> ${esc(registration.name)}</p><p><strong>E-mail:</strong> ${esc(registration.email)}</p><p><strong>Localização:</strong> ${esc(registration.city)}${registration.state ? ' · '+esc(registration.state) : ''}</p></div><label class="check-line"><input type="checkbox" name="terms" required><span>Li e concordo com os ${link('/termos-de-uso','Termos de Uso')} e a ${link('/politica-de-privacidade','Política de Privacidade')}.</span></label>`;
  return `<main class="auth-layout">${authSide(true)}<div class="auth-main"><div class="auth-form-wrap signup-wrap">${logo()}<div class="auth-title"><h1>Crie sua conta de Cidadão</h1><p>Já tem conta? ${link('/login','Entrar')}</p></div><div class="mini-progress">${steps.map((s,i)=>`<span class="${registration.step >= i+1 ? 'active' : ''}"></span>`).join('')}</div><p class="step-caption">${steps[registration.step-1]} · Passo ${registration.step} de 4</p><form id="signup-form" class="form-stack">${content}<div class="form-row">${registration.step > 1 ? '<button type="button" class="btn btn-ghost" data-action="signup-back">← Voltar</button>' : ''}<button class="btn btn-primary ${registration.step===1?'btn-full':''}" type="submit">${registration.step===4?'Criar Conta →':'Continuar →'}</button></div></form>${registration.step===1 ? '<div class="divider"><span>ou</span></div><button type="button" class="btn btn-google btn-full" data-action="google"><strong>G</strong> Cadastrar com Google</button>' : ''}</div></div></main>`;
}

function anonymous() { return `${header()}<main class="page-light"><div class="container narrow-page"><button class="back-link" data-action="back">← Voltar</button><div class="anonymous-banner"><span class="anon-lock">🔒</span><div><h2>Denúncia 100% Anônima</h2><p>Não solicitamos dados pessoais neste modo. Nesta demonstração, a denúncia fica somente neste navegador.</p></div></div><div class="form-card"><h1>Fazer Denúncia Anônima</h1><p class="subhead">Tem conta? ${link('/login','Entre para denúncias identificadas →')}</p><form id="anonymous-form" class="form-stack"><label class="field"><span>Categoria do Problema</span><select name="category" required><option value="">Selecione uma categoria…</option>${categories.map(c=>`<option value="${c[0]}">${c[1]} ${c[2]}</option>`).join('')}</select></label>${field('Endereço do Problema','address','Rua, Avenida, bairro, referência…','text','','required')}${field('Título / Resumo','title','Breve descrição do problema','text','','required')}<label class="field"><span>Descrição Detalhada</span><textarea name="description" placeholder="Descreva o problema com o máximo de detalhes possível…" rows="6" required></textarea></label><button class="btn btn-primary btn-full" type="submit">🔒 Enviar Denúncia Anônima</button></form></div></div></main>${footer()}`; }

function appStats() { const c = counts(); const metrics=[['📋',c.total,'Total de Denúncias','purple'],['✅',c.resolved,'Resolvidas','green'],['⏳',c.pending,'Pendentes','amber'],['🔄',c.progress,'Em Andamento','blue']]; return metrics.map(([icon,value,label,color])=>`<div class="stat-card ${color}"><span class="stat-icon">${icon}</span><strong>${value}</strong><span>${label}</span></div>`).join(''); }
function recentItems(reports) { return reports.length ? reports.slice(0,4).map(r=>`<article class="report-row"><div class="report-symbol">${categories.find(c=>c[0]===r.category)?.[1]||'📋'}</div><div class="report-content"><strong>${esc(r.title)}</strong><span>${esc(r.address || r.city || 'Localização não informada')} · ${esc(categoryName(r.category))}</span></div><span class="status ${r.status==='Resolvido'?'done':r.status==='Em Andamento'?'progress':'pending'}">${esc(r.status)}</span></article>`).join('') : `<div class="empty-inline"><p>Nenhuma denúncia ainda.</p>${buttonLink('/nova-denuncia','+ Nova Denúncia','btn-primary btn-small')}</div>`; }
function dashboard() { const c=counts(), m=counts(myReports()); return `${header(true)}<main class="dashboard-page"><div class="container"><div class="page-heading"><div><h1>Bom dia, ${esc(name())}! 👋</h1><p>Aqui está um resumo das atividades da plataforma LUMEN.</p></div></div><div class="dashboard-label">DADOS DO SITE</div><div class="stats-grid">${[['📋',c.total,'Total de Denúncias','purple'],['✅',c.resolved,'Resolvidas','green'],['🔄',c.progress,'Em Andamento','blue'],['👍',0,'Total de Apoios','amber']].map(([icon,value,label,color])=>`<div class="stat-card ${color}"><span class="stat-icon">${icon}</span><strong>${value}</strong><span>${label}</span></div>`).join('')}</div><div class="dashboard-label">MINHAS DENÚNCIAS</div><div class="stats-grid my-stats">${[[m.total,'Registradas'],[m.resolved,'Resolvidas'],[m.progress,'Em Andamento'],[m.pending,'Pendentes']].map(([value,label],i)=>link('/minhas-denuncias',`<strong>${value}</strong><span>${label}</span>`,`mini-stat tone-${i}`)).join('')}</div><div class="dash-columns"><div class="dash-main"><section class="panel"><div class="panel-head"><h2>Denúncias Recentes (Site)</h2>${link('/minhas-denuncias','Ver todas →')}</div>${recentItems([...data.reports].reverse())}</section><section class="panel"><h2>👍 Apoios Recebidos — Todas as Denúncias</h2><p class="muted">Sem apoios ainda.</p></section><section class="panel"><h2>Ações Rápidas</h2><div class="quick-grid">${[['📝','Nova Denúncia','/nova-denuncia'],['🔒','Denúncia Anônima','/denuncia-anonima'],['📊','Estatísticas','/estatisticas'],['⚙️','Configurações','/configuracoes']].map(([icon,label,url])=>link(url,`<span>${icon}</span>${label}`,'quick-action')).join('')}</div></section></div><div class="dash-side"><section class="panel"><div class="panel-head"><h2>Notificações</h2>${link('/notificacoes','Ver todas')}</div><p class="muted">🔔 Sem notificações ainda.<br>Elas aparecerão quando alguém interagir com suas denúncias.</p></section><section class="panel"><h2>Cidade em Números</h2>${[['Total de Denúncias',c.total],['Resolvidas',c.resolved],['Em Andamento',c.progress],['Total de Apoios',0]].map(([label,value])=>`<div class="number-line"><span>${label}</span><strong>${value}</strong></div>`).join('')}${link('/estatisticas','Ver relatório completo →','text-link')}</section></div></div></div></main>`; }

function newReport() {
  const q = new URLSearchParams(location.hash.split('?')[1] || '').get('categoria');
  if (q && !reportDraft.category) reportDraft.category=q;
  const step=reportDraft.step;
  let content='';
  if(step===1) content=`<h2>Categoria do Problema</h2><p>Selecione o tipo de problema que deseja relatar.</p><div class="category-grid">${categories.map(c=>`<button type="button" class="category-option ${reportDraft.category===c[0]?'selected':''}" data-category="${c[0]}"><span>${c[1]}</span>${c[2]}</button>`).join('')}</div>`;
  if(step===2) content=`<h2>Localização do Problema</h2><p>Informe onde o problema foi encontrado.</p><div class="form-stack">${field('Endereço','report-address','Rua, Avenida, número ou referência','text',reportDraft.address,'required')}${field('Bairro','report-district','Nome do bairro','text',reportDraft.district,'required')}${field('Cidade','report-city','Sua cidade','text',reportDraft.city,'required')}</div>`;
  if(step===3) content=`<h2>Detalhes da Denúncia</h2><p>Conte o que aconteceu para facilitar o encaminhamento.</p><div class="form-stack">${field('Título / Resumo','report-title','Breve descrição do problema','text',reportDraft.title,'required')}<label class="field"><span>Descrição Detalhada</span><textarea name="report-description" rows="6" placeholder="Descreva o problema com o máximo de detalhes possível…" required>${esc(reportDraft.description)}</textarea></label><label class="field"><span>Foto (opcional)</span><input name="report-photo" type="file" accept="image/*"></label></div>`;
  if(step===4) content=`<h2>Revise sua Denúncia</h2><p>Confira as informações antes de enviar.</p><div class="review-box"><p><strong>Categoria:</strong> ${esc(categoryName(reportDraft.category))}</p><p><strong>Local:</strong> ${esc(reportDraft.address)}, ${esc(reportDraft.district)} · ${esc(reportDraft.city)}</p><p><strong>Título:</strong> ${esc(reportDraft.title)}</p><p><strong>Descrição:</strong> ${esc(reportDraft.description)}</p></div>`;
  return `${header(true)}<main class="dashboard-page"><div class="container wizard-container">${link('/dashboard','← Dashboard','back-link')}<span class="breadcrumb-slash">/</span><h1>Nova Denúncia</h1><div class="wizard-steps">${['Categoria','Localização','Detalhes','Revisão'].map((s,i)=>`<div class="wizard-step ${step>=i+1?'active':''}"><span>${i+1}</span><small>${s}</small></div>`).join('')}</div><div class="form-card wizard-card">${content}<div class="wizard-actions"><button type="button" class="btn btn-ghost" data-action="report-back">${step===1?'← Cancelar':'← Voltar'}</button><button type="button" class="btn btn-primary" data-action="report-next">${step===4?'Enviar Denúncia →':'Continuar →'}</button></div></div></div></main>`;
}

function reportsPage() { const all=listScope==='all'?data.reports:myReports(); const shown=listFilter==='Todos'?all:all.filter(r=>r.status===listFilter); const c=counts(all); return `${header(true)}<main class="dashboard-page"><div class="container"><div class="breadcrumb">${link('/dashboard','← Dashboard')} <span>/</span></div><div class="page-heading"><h1>Denúncias</h1>${buttonLink('/nova-denuncia','+ Nova Denúncia','btn-primary btn-small')}</div><div class="tab-row"><button class="${listScope==='mine'?'selected':''}" data-scope="mine">Minhas Denúncias</button><button class="${listScope==='all'?'selected':''}" data-scope="all">Todas as Denúncias</button></div><div class="stats-grid list-stats">${[[c.total,'Total'],[c.pending,'Pendentes'],[c.progress,'Em Andamento'],[c.resolved,'Resolvidos']].map(([value,label])=>`<button class="mini-stat"><strong>${value}</strong><span>${label}</span></button>`).join('')}</div><div class="filter-row">${['Todos','Pendente','Em Andamento','Resolvido'].map(f=>`<button class="filter-chip ${listFilter===f?'selected':''}" data-filter="${f}">${f}</button>`).join('')}</div>${shown.length?`<div class="panel report-list">${[...shown].reverse().map(r=>`<article class="report-row"><div class="report-symbol">${categories.find(c=>c[0]===r.category)?.[1]||'📋'}</div><div class="report-content"><strong>${esc(r.title)}</strong><span>${esc(r.address || r.city)} · ${esc(categoryName(r.category))} · ${esc(r.protocol)}</span></div><span class="status pending">${esc(r.status)}</span></article>`).join('')}</div>`:`<div class="empty-state"><div>📭</div><h3>Nenhuma denúncia encontrada</h3><p>${listScope==='mine'?'Você ainda não fez nenhuma denúncia.':'Nenhuma denúncia registrada ainda.'}</p>${buttonLink('/nova-denuncia','Fazer primeira denúncia →','btn-primary')}</div>`}</div></main>`; }

function statsPage() { const c=counts(); const grouped=categories.map(cat=>[cat[2],data.reports.filter(r=>r.category===cat[0]).length]).filter(row=>row[1]); const h=header(true); return `${h}<main class="dashboard-page"><div class="container"><div class="page-heading"><div><h1>Estatísticas da Cidade</h1><p>Dados reais com base nas denúncias registradas na plataforma.</p></div>${buttonLink('/nova-denuncia','+ Nova Denúncia','btn-primary btn-small')}</div><div class="stats-grid">${appStats()}</div><div class="two-columns"><section class="panel"><h3>Relatórios por Categoria</h3>${grouped.length?grouped.map(([label,value])=>`<div class="number-line"><span>${esc(label)}</span><strong>${value}</strong></div>`).join(''):'<p class="muted">Nenhuma denúncia registrada ainda.</p>'}</section><section class="panel"><h3>Relatórios por Bairro</h3>${data.reports.some(r=>r.district)?[...new Set(data.reports.map(r=>r.district).filter(Boolean))].map(d=>`<div class="number-line"><span>${esc(d)}</span><strong>${data.reports.filter(r=>r.district===d).length}</strong></div>`).join(''):'<p class="muted">Nenhuma denúncia com bairro informado.</p>'}</section></div><section class="panel"><div class="panel-head"><h3>Denúncias Registradas</h3>${link('/minhas-denuncias','Ver todas →')}</div>${data.reports.length?recentItems([...data.reports].reverse()):`<div class="empty-inline"><p>📭</p><p>Nenhuma denúncia registrada ainda.</p>${buttonLink('/minhas-denuncias','Ver todos os relatórios','btn-primary btn-small')}</div>`}</section></div></main>`; }

function notificationsPage() { const notices=data.notifications.filter(n=>n.userId===data.currentUser?.email); return `${header(true)}<main class="dashboard-page"><div class="container"><div class="page-heading"><h1>Notificações</h1>${buttonLink('/configuracoes','⚙️ Preferências','btn-outline btn-small')}</div>${notices.length?`<div class="panel">${notices.map(n=>`<article class="report-row"><div class="report-symbol">🔔</div><div class="report-content"><strong>${esc(n.title)}</strong><span>${esc(n.body)}</span></div></article>`).join('')}</div>`:`<div class="empty-state"><div>🔔</div><h3>Nenhuma notificação</h3><p>As notificações aparecerão aqui quando alguém comentar ou apoiar suas denúncias.</p>${buttonLink('/nova-denuncia','Fazer uma denúncia →','btn-primary')}</div>`}<div class="center-back">${link('/dashboard','← Voltar ao Dashboard','back-link')}</div></div></main>`; }

function about() { return `${header()}<main class="page-light"><div class="container article-page"><button class="back-link" data-action="back">← Voltar</button><h1>Sobre a LUMEN</h1><section class="panel"><h2>Nossa Missão</h2><p>Conectar cidadãos e administração pública através da tecnologia, tornando cidades mais transparentes, responsivas e humanas. Acreditamos que cada voz conta — e que a tecnologia cívica pode transformar a gestão do espaço urbano.</p></section><section class="panel"><h2>O que é a LUMEN?</h2><p>A LUMEN é uma plataforma de participação cidadã que permite a qualquer pessoa registrar e acompanhar problemas urbanos diretamente junto às autoridades competentes. Desde buracos em vias públicas até falhas na iluminação, passando por questões de saneamento e segurança.</p><p>Fundada em 2023, a plataforma já conectou mais de <strong>12.400 cidadãos</strong> com os órgãos municipais, com uma taxa de resolução de <strong>89%</strong> das denúncias em menos de 5 dias.</p></section><h2>Como Funcionamos</h2><div class="feature-cards about-features">${[['🔓','Transparência Total','Todas as denúncias são públicas. Cidadãos podem acompanhar e apoiar problemas de sua comunidade.'],['🔒','Privacidade Garantida','Seguimos rigorosamente a LGPD. Denúncias anônimas não coletam nenhum dado pessoal.'],['⚡','Resposta Rápida','Integramos diretamente com os sistemas das prefeituras para encaminhamento automático.'],['📊','Dados Abertos','Estatísticas públicas para jornalistas, pesquisadores e gestores públicos.']].map(([icon,title,desc])=>`<article class="feature-card"><span>${icon}</span><h3>${title}</h3><p>${desc}</p></article>`).join('')}</div><h2>Nossa Equipe</h2><div class="team-grid">${[['AC','Ana Costa','CEO & Co-fundadora'],['BL','Bruno Lima','CTO & Co-fundador'],['CM','Carla Mendes','Head de Produto'],['DR','Diego Rocha','Head de Parcerias']].map(([initials,n,role])=>`<div class="team-card"><div>${initials}</div><strong>${n}</strong><span>${role}</span></div>`).join('')}</div><div class="inline-actions">${buttonLink('/cadastro','Fazer Parte da LUMEN →','btn-primary')}${buttonLink('/termos-de-uso','Termos de Uso','btn-outline')}</div></div></main>${footer()}`; }

function simplePage(type) { const forgot=type==='forgot', config=type==='config', privacy=type==='privacy'; const title=forgot?'Esqueci a Senha':config?'Configurações':privacy?'Política de Privacidade':'Termos de Uso'; return `${header(config)}<main class="page-light"><div class="container narrow-page"><div class="form-card simple-card">${link(config?'/dashboard':'/home','← Voltar','back-link')}<h1>${title}</h1>${forgot?`<p>Informe seu e-mail para recuperar o acesso à sua conta.</p><form id="forgot-form" class="form-stack">${field('E-mail','forgot-email','seu@email.com','email','','required')}<button class="btn btn-primary" type="submit">Enviar instruções →</button></form>`:config?`<p>Gerencie suas preferências da plataforma.</p><div class="number-line"><span>Notificações por e-mail</span><label class="switch"><input type="checkbox" checked><span></span></label></div><div class="number-line"><span>Notificações de andamento</span><label class="switch"><input type="checkbox" checked><span></span></label></div>`:`<p>Este front end reproduz o conteúdo visual do protótipo LUMEN. ${privacy?'Os dados preenchidos nesta demonstração ficam apenas no navegador usado, em armazenamento local.':'Ao utilizar esta demonstração, você pode testar os fluxos visuais e formulários localmente.'}</p><p>Para uma operação real, a plataforma precisa de termos completos, política de privacidade, autenticação e infraestrutura de processamento de denúncias.</p>`}</div></div></main>${footer()}`; }

function forgotPage() { return `<main class="auth-layout">${authSide(false,true)}<div class="auth-main"><div class="auth-form-wrap">${logo()}${link('/login','← Voltar ao login','back-link')}<div class="auth-title"><h1>Esqueci minha senha</h1><p>Informe o e-mail cadastrado e enviaremos um link para criar nova senha.</p></div><form id="forgot-form" class="form-stack">${field('E-mail cadastrado','forgot-email','seu@email.com','email','','required')}<button class="btn btn-primary btn-full" type="submit">Enviar link de recuperação</button></form><p class="auth-legal">Lembrou a senha? ${link('/login','Voltar ao login')}</p></div></div></main>`; }
function configPage() { return `${header(true)}<main class="dashboard-page"><div class="container settings-container"><div class="breadcrumb">${link('/dashboard','← Perfil')} <span>/</span></div><h1>Configurações</h1><section class="panel settings-panel"><h2>🔔 Notificações</h2><p>Gerencie como quer ser informado.</p>${[['E-mail','Notificações sobre denúncias por e-mail',true],['Push (navegador)','Notificações em tempo real no navegador',false],['Newsletter','Novidades e relatórios mensais da cidade',true]].map(([label,desc,checked],i)=>`<label class="setting-row"><span><strong>${label}</strong><small>${desc}</small></span><input type="checkbox" data-pref="${i}" ${checked?'checked':''}></label>`).join('')}${link('/notificacoes','Ver histórico de notificações →','text-link')}</section><section class="panel settings-panel"><h2>🔒 Privacidade</h2><p>Controle a visibilidade das suas informações.</p><label class="setting-row"><span><strong>Perfil público</strong><small>Outros cidadãos podem ver seu perfil</small></span><input type="checkbox" data-pref="public"></label><p class="form-hint">ℹ️ Saiba mais na nossa ${link('/politica-de-privacidade','Política de Privacidade')}.</p></section><section class="panel settings-panel"><h2>🔑 Segurança da Conta</h2><form id="password-form" class="form-stack">${field('Senha Atual','current-password','••••••••','password','','required')}${field('Nova Senha','new-password','Mínimo 8 caracteres','password','','required minlength="8"')}${field('Confirmar Nova Senha','confirm-password','Repita a nova senha','password','','required minlength="8"')}<button class="btn btn-primary" type="submit">Atualizar Senha</button></form></section><section class="panel settings-panel"><h2>📄 Documentos Legais</h2>${[['Termos de Uso','/termos-de-uso'],['Política de Privacidade','/politica-de-privacidade'],['Sobre a LUMEN','/sobre']].map(([label,url])=>link(url,`<span>${label}</span><strong>Ver →</strong>`,'setting-row')).join('')}</section><section class="panel settings-panel"><h2>⚠️ Zona de Perigo</h2><p>Ações irreversíveis. Proceda com cuidado.</p><div class="inline-actions"><button class="btn btn-outline" type="button" data-action="export-data">📤 Exportar Meus Dados</button><button class="btn btn-outline" type="button" data-action="delete-disabled">🗑️ Excluir Conta</button></div></section></div></main>`; }
function successPage() { const protocol=sessionStorage.getItem('lumen-last-protocol') || 'LMN-2024-000'; return `${header(true)}<main class="page-light"><div class="container narrow-page"><div class="empty-state success-state"><div>✅</div><h1>Denúncia enviada!</h1><p>Seu registro foi salvo nesta demonstração.</p><div class="protocol">${esc(protocol)}</div>${buttonLink('/minhas-denuncias','Ver denúncias','btn-primary')}${link('/home','Voltar ao início','text-link')}</div></div></main>`; }

function render() {
  const p=path(); const app=$('#app');
  app.innerHTML=({ '/home':home,'/':home,'/login':login,'/cadastro':signup,'/denuncia-anonima':anonymous,'/dashboard':dashboard,'/nova-denuncia':newReport,'/minhas-denuncias':reportsPage,'/estatisticas':statsPage,'/notificacoes':notificationsPage,'/sobre':about,'/esqueci-senha':forgotPage,'/configuracoes':configPage,'/termos-de-uso':()=>simplePage('terms'),'/politica-de-privacidade':()=>simplePage('privacy'),'/denuncia-enviada':successPage})[p]?.() || home();
  document.title=`${({'/home':'Sua voz transforma a cidade','/login':'Entrar','/cadastro':'Criar conta','/dashboard':'Dashboard','/nova-denuncia':'Nova denúncia','/denuncia-anonima':'Denúncia anônima','/estatisticas':'Estatísticas','/minhas-denuncias':'Denúncias','/notificacoes':'Notificações','/sobre':'Sobre a LUMEN','/esqueci-senha':'Recuperar senha','/configuracoes':'Configurações','/termos-de-uso':'Termos de Uso','/politica-de-privacidade':'Política de Privacidade','/denuncia-enviada':'Denúncia enviada'})[p]||'LUMEN'} — LUMEN`;
  if(p==='/configuracoes') app.querySelectorAll('[data-pref]').forEach(input=>{if(data.preferences?.[input.dataset.pref]!==undefined) input.checked=data.preferences[input.dataset.pref];});
  if(!location.hash) location.replace('#/home');
}
function showToast(message){ let t=$('#toast'); if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.appendChild(t);} t.textContent=message;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),3600); }
function collectRegistration(){ for(const [id,key] of [['reg-name','name'],['reg-email','email'],['reg-cpf','cpf'],['reg-phone','phone'],['reg-city','city'],['reg-state','state'],['reg-password','password']]){const el=document.getElementById(id)||document.querySelector(`[name="${id}"]`);if(el)registration[key]=el.value.trim();} }
function collectReport(){ for(const [id,key] of [['report-address','address'],['report-district','district'],['report-city','city'],['report-title','title'],['report-description','description']]){const el=document.getElementById(id)||document.querySelector(`[name="${id}"]`);if(el)reportDraft[key]=el.value.trim();} }

document.addEventListener('click',event=>{
  const el=event.target.closest('[data-action],[data-category],[data-scope],[data-filter]'); if(!el)return;
  if(el.dataset.category){ reportDraft.category=el.dataset.category; render(); return; }
  if(el.dataset.scope){ listScope=el.dataset.scope; render(); return; }
  if(el.dataset.filter){ listFilter=el.dataset.filter; render(); return; }
  const action=el.dataset.action;
  if(action==='toggle-menu') $('#mobile-menu')?.classList.toggle('open');
  if(action==='account-menu') $('#account-menu')?.classList.toggle('open');
  if(action==='logout'){data.currentUser=null;save();location.hash='/home';showToast('Você saiu da conta.');}
  if(action==='google') showToast('Login com Google requer uma integração externa.');
  if(action==='delete-disabled') showToast('Exclusão de conta indisponível nesta demonstração local.');
  if(action==='export-data'){
    const exportable={user:data.currentUser,reports:myReports()};
    const url=URL.createObjectURL(new Blob([JSON.stringify(exportable,null,2)],{type:'application/json'}));
    const download=document.createElement('a');download.href=url;download.download='lumen-meus-dados.json';download.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
  }
  if(action==='back') history.length>1?history.back():location.hash='/home';
  if(action==='toggle-password'){ const input=el.parentElement.querySelector('input');input.type=input.type==='password'?'text':'password';el.textContent=input.type==='password'?'👁️':'🙈'; }
  if(action==='signup-back'){collectRegistration();registration.step=Math.max(1,registration.step-1);render();}
  if(action==='report-back'){collectReport();if(reportDraft.step===1)location.hash='/dashboard';else{reportDraft.step--;render();}}
  if(action==='report-next'){
    collectReport(); const step=reportDraft.step;
    if(step===1&&!reportDraft.category)return showToast('Selecione uma categoria.');
    if(step===2&&(!reportDraft.address||!reportDraft.district||!reportDraft.city))return showToast('Preencha a localização.');
    if(step===3&&(!reportDraft.title||!reportDraft.description))return showToast('Preencha os detalhes.');
    if(step<4){reportDraft.step++;render();window.scrollTo(0,0);return;}
    const protocol=`LMN-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`;
    data.reports.push({...reportDraft,protocol,status:'Pendente',userId:data.currentUser?.email||'visitante',createdAt:new Date().toISOString()});save();sessionStorage.setItem('lumen-last-protocol',protocol);reportDraft={step:1,category:'',address:'',district:'',city:'',title:'',description:'',photo:''};location.hash='/denuncia-enviada';
  }
});
document.addEventListener('change',event=>{if(event.target.matches('[data-pref]')){data.preferences={...(data.preferences||{}),[event.target.dataset.pref]:event.target.checked};save();}});
async function digest(value){ const bytes=new TextEncoder().encode(value); const hash=await crypto.subtle.digest('SHA-256',bytes); return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join(''); }
document.addEventListener('submit',async event=>{
  const form=event.target;event.preventDefault();
  if(form.id==='login-form'){
    const email=form.querySelector('[name="email"]').value.trim().toLowerCase(),password=form.querySelector('[name="password"]').value;
    const passwordHash=await digest(password);
    const user=data.users.find(u=>u.email===email&&u.passwordHash===passwordHash);
    if(!user)return showToast('E-mail ou senha inválidos nesta demonstração. Crie uma conta para testar.');
    data.currentUser={name:user.name,email:user.email};save();location.hash='/dashboard';
  }
  if(form.id==='signup-form'){
    collectRegistration();
    if(registration.step===3&&form['reg-confirm'].value!==registration.password)return showToast('As senhas não coincidem.');
    if(registration.step<4){registration.step++;render();window.scrollTo(0,0);return;}
    if(data.users.some(u=>u.email===registration.email.toLowerCase()))return showToast('Este e-mail já foi cadastrado.');
    const user={name:registration.name,email:registration.email.toLowerCase(),city:registration.city,state:registration.state,passwordHash:await digest(registration.password)};data.users.push(user);data.currentUser={name:user.name,email:user.email};save();registration={step:1,name:'',email:'',cpf:'',phone:'',city:'',state:'',password:''};location.hash='/dashboard';
  }
  if(form.id==='anonymous-form'){
    const values=new FormData(form);const protocol=`LMN-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`;
    data.reports.push({protocol,category:values.get('category'),address:values.get('address'),title:values.get('title'),description:values.get('description'),status:'Pendente',userId:null,createdAt:new Date().toISOString()});save();listScope='all';sessionStorage.setItem('lumen-last-protocol',protocol);location.hash='/denuncia-enviada';
  }
  if(form.id==='forgot-form')showToast('Esta demonstração não envia e-mails. Para testar, crie uma conta local.');
  if(form.id==='password-form'){
    const user=data.users.find(u=>u.email===data.currentUser?.email);
    const current=form.querySelector('[name="current-password"]').value;
    const next=form.querySelector('[name="new-password"]').value;
    const confirm=form.querySelector('[name="confirm-password"]').value;
    if(!user||user.passwordHash!==await digest(current))return showToast('Senha atual incorreta.');
    if(next!==confirm)return showToast('As novas senhas não coincidem.');
    user.passwordHash=await digest(next);save();form.reset();showToast('Senha atualizada nesta demonstração.');
  }
});
window.addEventListener('hashchange',()=>{if(path()==='/nova-denuncia'){const cat=new URLSearchParams(location.hash.split('?')[1]||'').get('categoria');if(cat)reportDraft.category=cat;}render();window.scrollTo(0,0);});
render();
